version: '3.8'

services:

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: geniltonbd
      POSTGRES_PASSWORD: admin123

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
